### ISSUE TITLE
1.3.0 breaks python-2 compatability with call to super()

### ISSUE THREAD

**Issue by martinwilkerson-scisys** [adamchainz/django-jsonfield#15]
Won't be an issue for much longer, but python 2 has still not reached EOL and the change for 1.3.0 added a call to `super()` with no arguments, which is not valid in python 2.

**Comment by adamchainz** [comment]
...still a bug since this package advertises Python 2 compat! The dangers of not having CI set up :(

Released in version 1.3.1 ! https://pypi.org/project/django-jsonfield/1.3.1/

Thanks for the report.
