### ISSUE TITLE
django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy()

### ISSUE THREAD

**Issue by Ben-yeah** [adamchainz/django-jsonfield#22]
Hello, The only thing I'm personally see wrong with Treebeard and Django 3.0 is that 3.0 officially deprecated ugettext_lazy, and if you run python -Wall, you'll get a ton of RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().

**Comment by adamchainz** [comment]
It seems django-treebeard doesn't use django-jsonfield? I think you posted this issue against the wrong repository.
