### ISSUE TITLE
Release 1.4.1 is not tagged

### ISSUE THREAD

**Issue by PabloCastellano** [adamchainz/django-jsonfield#23]
django-jsonfield 1.4.1 is available on Pypi but it's not tagged in the repository

**Comment by adamchainz** [comment]
Fixed.

**Comment by adamchainz** [comment]
Why do you want the tag?

**Comment by PabloCastellano** [comment]
It was confusing coming here to check the latest version available (1.4.0) and get to install 1.4.1 using pip. Thanks!

**Comment by adamchainz** [comment]
Okay fair.
