### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by ktrls** [adamchainz/django-jsonfield#24]
Hi, I'm trying to install this module by pip in a django 1.8 project, but during installation step this remove the 1.8 version and install 1.9.

Is this a normal behavior? I read that the module is compatible with 1.8.
What am I doing wrong?

Thanks in advance

**Comment by adamchainz** [comment]
Sorry, I'm not maintaining this any more, and your Django version is well past support. Please just work on upgrading.
